### ISSUE TITLE
Description of script

### ISSUE THREAD

**Issue by heigler** [ReidKleman/bittrexTrade#1]
Your script is very interesting, but what it does exaclty?
The bot buys some altcoin using 75% of your current BTC amount, wait 10 seconds, and then it creates a sell order with a target of 1.025%, it repeat the process for 1 minute, and then restarts everything, is that right?

I'm very curious how can you use that to make some profit  (I'm new on trading) :D

**Comment by ReidKleman** [comment]
Hey I'm sorry I was off GitHub for a while but you were exactly right if it still helps I only used 75% of my bitcoins because I didn't want to loose all my bitcoin if the trade somehow went completely south I waited 10 seconds because if I spammed the API it would lock me out(I think but I'm not exactly sure why I did that lol)
